%YAML 1.2
---
sweep_options:
  Cycle_Length:
      - 3
      - 4
  Chain_Length:
      - 3
      - 4
  VertexBudget:
      #- 1
      - 2
      - 3
      - 4
  ArcBudget:
      - 0
      #- 10
      #- 30
      #- 3
  Policy:
      - "Full"
      #- "FirstSOnly"
  Formulation:
      - "Covering"
      - "DoubleCovering"
      #- "Benders"
      #- "BendersPICEF"
  LowerBound:
      - "NoBound"

run_setup:
  OutputPath: "outputs/RO_results_benchmark.txt"
  TimeLimit: 3600
  InstanceFolders:
    #- "20"
    #- "50"
    - "100"
  InstancesDir: "/home/criascos/codes/0TestInstances/ROCarvalho2021"
  exe: "./2StageROThisWork"
  LogPrintFolder: "outputs/benchmark"

